language: elixir
elixir: '1.6.5'
sudo: required
services:
  - redis-server
notifications:
  email: false
env:
  - MIX_ENV=test
script:
  - mix format --check-formatted
  - mix credo
  - mix test
#- mix coveralls.travis
