language: elixir
elixir: '1.8.1'
otp_release: '21.3'
sudo: required
services:
  - redis-server
notifications:
  email: false
env:
  - MIX_ENV=test
before_script:
  - mix compile 
  - travis_wait mix dialyzer --plt

script:
  - mix deps.get
  - mix test
  - MIX_ENV=dev travis_wait 20 mix dialyzer --halt-exit-status
#- mix coveralls.travis

cache:
  directories:
    - priv/plts
