language: elixir
elixir: '1.7.0'
otp_release: '21.0'
sudo: required
services:
  - redis-server
notifications:
  email: false
env:
  - MIX_ENV=test
script:
  - mix deps.get
  - mix test
#- mix coveralls.travis
