language: elixir
elixir: '1.9.2'
otp_release: '22.0.7'
sudo: required
services:
  - redis-server
notifications:
  email: false
env:
  - MIX_ENV=test

before_script:
  - mix do deps.get, compile --warnings-as-errors, coveralls.json
  - MIX_ENV=dev travis_wait 30 mix dialyzer --plt

script:
  - mix test
  - MIX_ENV=dev mix dialyzer --halt-exit-status
#- mix coveralls.travis

after_success:
  - bash <(curl -s https://codecov.io/bash)

cache:
  directories:
    - priv/plts
