language: elixir
elixir: '1.7.3'
otp_release: '21.3'
sudo: required
services:
  - redis-server
notifications:
  email: false
env:
  - MIX_ENV=test

before_script:
  - mix do compile --warnings-as-errors, coveralls.json
  - MIX_ENV=dev travis_wait 20 mix dialyzer --plt

script:
  - mix format --check-formatted
  - mix credo
  - mix test
  - MIX_ENV=dev mix dialyzer --halt-exit-status
#- mix coveralls.travis

after_success:
  - bash <(curl -s https://codecov.io/bash)

cache:
  directories:
    - priv/plts
