on: [push, pull_request]
name: Continuous Integration
jobs:
  test:
    runs-on: ubuntu-latest

    env:
      MIX_ENV: test

    strategy:
      matrix:
        otp: [23.3.4, 24.0.2]
        elixir: [1.11.4, 1.12.1]

    steps:
      - uses: actions/checkout@v3

      - name: Cache dialyzer plts
        uses: actions/cache@v3
        with:
          path: priv/plts
          key: ${{runner.os}}-${{matrix.otp}}-${{matrix.elixir}}-plts

      - uses: erlef/setup-elixir@v1
        with:
          otp-version: ${{matrix.otp}}
          elixir-version: ${{matrix.elixir}}

      - name: Deps get and check unused
        run: mix deps.get && mix deps.unlock --check-unused

      - name: Check Credo
        run: mix credo

      - name: Check Formatting
        if: ${{ matrix.elixir != '1.11.4' }}
        run: mix format --check-formatted

      - name: Run Tests
        run: mix do compile --warnings-as-errors, test

      - name: Dialyzer
        run: mix dialyzer --halt-exit-status
